Repository juaml/junifer, pull requests merged in 2022-09, with the labels that each got.

#63 docs: `junifer` + `julearn` example
  docs/changes/latest.inc
  examples/run_junifer_julearn.py
  pyproject.toml
Labels: documentation

#71 Feat/coordinates
  docs/changes/latest.inc
  junifer/data/VOIs/meta/CogAC_VOIs.txt
  junifer/data/VOIs/meta/CogAR_VOIs.txt
  junifer/data/VOIs/meta/DMNBuckner_VOIs.txt
  junifer/data/VOIs/meta/Empathy_VOIs.txt
  junifer/data/VOIs/meta/Motor_VOIs.txt
  junifer/data/VOIs/meta/MultiTask_VOIs.txt
  junifer/data/VOIs/meta/PhysioStress_VOIs.txt
  junifer/data/VOIs/meta/Rew_VOIs.txt
  junifer/data/VOIs/meta/Somatosensory_VOIs.txt
  junifer/data/VOIs/meta/ToM_VOIs.txt
  junifer/data/VOIs/meta/VigAtt_VOIs.txt
  junifer/data/VOIs/meta/WM_VOIs.txt
  junifer/data/VOIs/meta/eMDN_VOIs.txt
  junifer/data/VOIs/meta/eSAD_VOIs.txt
  junifer/data/VOIs/meta/extDMN_VOIs.txt
  junifer/data/coordinates.py
  junifer/data/tests/test_coordinates.py
Labels: enhancement

#76 Add data grabber for AOMIC1000 dataset
  docs/changes/contributors.inc
  docs/changes/latest.inc
  junifer/datagrabber/aomic1000.py
  junifer/datagrabber/tests/test_aomic1000.py
  tools/create_aomic1000_example_dataset.py
Labels: dataset

#59 feat: add support for ETSRSS marker
  docs/changes/contributors.inc
  docs/changes/latest.inc
  examples/run_ets_rss_marker.py
  junifer/data/coordinates.py
  junifer/data/tests/test_coordinates.py
  junifer/datagrabber/tests/test_datagrabber_utils.py
  junifer/datagrabber/tests/test_pattern.py
  junifer/datagrabber/utils.py
  junifer/markers/__init__.py
  junifer/markers/ets_rss.py
  junifer/markers/functional_connectivity_atlas.py
  junifer/markers/tests/test_ets_rss.py
  junifer/markers/tests/test_functional_connectivity_atlas.py
  junifer/markers/tests/test_marker_utils.py
  junifer/markers/tests/test_markers_base.py
  junifer/markers/tests/test_parcel.py
  junifer/markers/tests/test_sphere_aggregation.py
  junifer/markers/utils.py
  junifer/testing/tests/test_testing_registry.py
  junifer/tests/test_stats.py
Labels: enhancement, marker

#70 Changes to documentation in FAQs and built-in components
  docs/builtin.rst
  docs/contribution.rst
  docs/faq.rst
Labels: documentation
