Repository juaml/junifer, pull requests merged in 2022-10, with the labels that each got.

#50 [ENH] Move `junifer.api.registry` to `junifer.pipeline`
  junifer/api/__init__.py
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/pipeline/registry.py
  junifer/pipeline/tests/test_registry.py
  junifer/testing/registry.py
  junifer/testing/tests/test_testing_registry.py
Labels: enhancement

#33 [ENH]: Implement a command to print the running environment details
  junifer/api/cli.py
  junifer/api/tests/test_api_utils.py
  junifer/api/tests/test_cli.py
  junifer/api/utils.py
Labels: enhancement

#9 [ENH] Implement `junifer selftest` to allow the users to test the library themselves
  junifer/api/cli.py
  junifer/api/tests/test_cli.py
Labels: enhancement, ready

#39 [DOC]: Provide a thorough description on how junifer works
  README.md
  docs/builtin.rst
  docs/conf.py
  docs/images/junifer_logo.png
  docs/index.rst
  docs/installation.rst
  docs/understanding/data.rst
  docs/understanding/datagrabber.rst
  docs/understanding/datareader.rst
  docs/understanding/index.rst
  docs/understanding/marker.rst
  docs/understanding/preprocess.rst
  docs/understanding/storage.rst
Labels: documentation, ready

#108 update: complete type annotations for DefaultDataReader
  junifer/datareader/default.py
Labels: enhancement, ready

#109 [ENH] Refactor markers
  docs/changes/latest.inc
  examples/run_compute_parcel_mean.py
  junifer/markers/__init__.py
  junifer/markers/base.py
  junifer/markers/ets_rss.py
  junifer/markers/functional_connectivity_atlas.py
  junifer/markers/functional_connectivity_spheres.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/markers/tests/test_functional_connectivity_atlas.py
  junifer/markers/tests/test_markers_base.py
  junifer/markers/tests/test_parcel.py
  scratch/test_niftimasker.py
Labels: ready

#57 feat: add grabber for local VBM AOMIC 1000 dataset
  docs/changes/contributors.inc
  docs/changes/latest.inc
  junifer/configs/juseless/datagrabbers/__init__.py
  junifer/configs/juseless/datagrabbers/aomic_id1000_vbm.py
  junifer/configs/juseless/datagrabbers/tests/test_aomic_id1000_vbm.py
Labels: ready

#93 update: add DataladHCP1200 datagrabber test
  docs/changes/latest.inc
  junifer/datagrabber/hcp.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/tests/test_hcp.py
  tools/create_hcp1200_example_dataset.py
Labels: ready
