Repository juaml/junifer, pull requests merged in 2022-12, with the labels that each got.

#151 update: add singleton decorator function for markers in `junifer.markers.utils`
  docs/changes/latest.inc
  junifer/markers/utils.py
Labels: ready

#152 refactor: improve `PipelineStepMixin` implementation
  docs/changes/latest.inc
  docs/installation.rst
  junifer/api/cli.py
  junifer/api/res/afni/3dReHo
  junifer/api/res/afni/afni
  junifer/api/res/afni/run_afni_docker.sh
  junifer/datareader/default.py
  junifer/datareader/tests/test_default_reader.py
  junifer/markers/base.py
  junifer/pipeline/pipeline_step_mixin.py
  junifer/pipeline/tests/test_pipeline_step_mixin.py
  junifer/pipeline/utils.py
  junifer/preprocess/base.py
  pyproject.toml
Labels: ready

#153 update: add AFNI to CI
  .github/workflows/ci-docs.yml
  .github/workflows/ci.yml
Labels: ready

#36 [MARKER]: ReHo
  .github/workflows/ci.yml
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/api/cli.py
  junifer/api/res/afni/3dAFNItoNIFTI
  junifer/markers/__init__.py
  junifer/markers/reho/__init__.py
  junifer/markers/reho/reho_base.py
  junifer/markers/reho/reho_estimator.py
  junifer/markers/reho/reho_parcels.py
  junifer/markers/reho/reho_spheres.py
  junifer/markers/reho/tests/test_reho_estimator.py
  junifer/markers/reho/tests/test_reho_parcels.py
  junifer/markers/reho/tests/test_reho_spheres.py
  junifer/markers/tests/test_crossparcellation_functional_connectivity.py
  junifer/markers/tests/test_sphere_aggregation.py
  junifer/markers/utils.py
  junifer/pipeline/tests/test_pipeline_step_mixin.py
  junifer/storage/sqlite.py
  tox.ini
Labels: enhancement, marker, ready

#35 [MARKER]: (f)ALFF
  docs/builtin.rst
  docs/changes/latest.inc
  docs/conf.py
  junifer/api/res/afni/3dRSFC
  junifer/markers/__init__.py
  junifer/markers/falff/__init__.py
  junifer/markers/falff/falff_base.py
  junifer/markers/falff/falff_estimator.py
  junifer/markers/falff/falff_parcels.py
  junifer/markers/falff/falff_spheres.py
  junifer/markers/falff/tests/test_falff_estimator.py
  junifer/markers/falff/tests/test_falff_parcels.py
  junifer/markers/falff/tests/test_falff_spheres.py
Labels: enhancement, marker, ready

#156 release: 0.0.1
  README.md
  docs/changes/0.0.1.inc
  docs/changes/latest.inc
  docs/index.rst
  docs/installation.rst
  docs/maintaining.rst
  docs/whats_new.rst
Labels: ready

#157 docs: fix typo
  docs/using/codeless.rst
  junifer/markers/falff/falff_base.py
  junifer/markers/falff/falff_estimator.py
  junifer/markers/falff/falff_parcels.py
  junifer/markers/falff/falff_spheres.py
  junifer/markers/falff/tests/test_falff_estimator.py
  junifer/markers/falff/tests/test_falff_parcels.py
  junifer/markers/falff/tests/test_falff_spheres.py
Labels: documentation, ready

#160 update: expose `PartlyCloudyTestingDataGrabber` to `testing.registry`
  docs/changes/latest.inc
  junifer/testing/registry.py
Labels: dataset, ready

#159 [BUG]: Preprocess step is not respected by `junifer run`
  docs/changes/latest.inc
  junifer/api/cli.py
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/markers/collection.py
  junifer/markers/tests/test_collection.py
Labels: bug, ready

#158 [BUG]: `PatternDataGrabber` does not respect the `"format"` parameter required for `BOLD_confounds` data type
  docs/changes/latest.inc
  junifer/configs/juseless/datagrabbers/ucla.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/tests/test_pattern.py
Labels: bug, dataset, ready
