Repository juaml/junifer, pull requests merged in 2022-11, with the labels that each got.

#112 [ENH]: Add support for python 3.11
  .github/workflows/ci-docs.yml
  .github/workflows/ci.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pypi.yml
  pyproject.toml
  tox.ini
Labels: enhancement, ready

#114 Fix/sphinx
  .github/workflows/pypi.yml
  docs/Makefile
  docs/_static/css/custom.css
  docs/_static/js/custom.js
  docs/_templates/versions.html
  docs/api/api.rst
  docs/api/configs.rst
  docs/api/data.rst
  docs/api/index.rst
  docs/api/pipeline.rst
  docs/api/stats.rst
  docs/builtin.rst
  docs/changes/latest.inc
  docs/conf.py
  docs/understanding/datagrabber.rst
  junifer/api/__init__.py
  junifer/configs/juseless/datagrabbers/aomic_id1000_vbm.py
  junifer/configs/juseless/datagrabbers/camcan_vbm.py
  junifer/configs/juseless/datagrabbers/ixi_vbm.py
  junifer/configs/juseless/datagrabbers/ukb_vbm.py
  junifer/data/atlases.py
  junifer/data/coordinates.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/base.py
  junifer/datagrabber/datalad_base.py
  junifer/datagrabber/hcp.py
  junifer/datagrabber/multiple.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/pattern_datalad.py
  junifer/markers/base.py
  junifer/markers/collection.py
  junifer/markers/ets_rss.py
  junifer/markers/functional_connectivity_atlas.py
  junifer/markers/functional_connectivity_spheres.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/stats.py
  junifer/storage/base.py
  junifer/storage/pandas_base.py
  junifer/storage/sqlite.py
  junifer/testing/datagrabbers.py
  pyproject.toml
  tox.ini
Labels: ready

#119 chore: standardize Sphinx section header ordering format
  .github/workflows/ci-docs.yml
  docs/api/api.rst
  docs/api/configs.rst
  docs/api/data.rst
  docs/api/datagrabbers.rst
  docs/api/datareaders.rst
  docs/api/index.rst
  docs/api/markers.rst
  docs/api/pipeline.rst
  docs/api/preprocessing.rst
  docs/api/stats.rst
  docs/api/storage.rst
  docs/api/testing.rst
  docs/api/utils.rst
  docs/builtin.rst
  docs/contribution.rst
  docs/faq.rst
  docs/installation.rst
  docs/maintaining.rst
  docs/understanding/data.rst
  docs/understanding/datagrabber.rst
  docs/understanding/datareader.rst
  docs/understanding/marker.rst
  docs/understanding/preprocess.rst
  docs/understanding/storage.rst
Labels: ready

#111 WIP: Preprocess
  docs/changes/latest.inc
  docs/links.inc
  docs/understanding/preprocess.rst
  junifer/api/decorators.py
  junifer/preprocess/__init__.py
  junifer/preprocess/base.py
  junifer/preprocess/confounds.py
  junifer/preprocess/confounds/__init__.py
  junifer/preprocess/confounds/fmriprep_confound_remover.py
  junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py
  junifer/preprocess/tests/test_confounds.py
  junifer/preprocess/tests/test_preprocess_base.py
  junifer/testing/__init__.py
  junifer/testing/data/sub-0001_task-anticipation_acq-seq_desc-confounds_regressors.tsv
  junifer/testing/datagrabbers.py
  junifer/testing/tests/test_oasisvmbtesting_datagrabber.py
  junifer/testing/tests/test_partlycloudytesting_datagrabber.py
  junifer/testing/utils.py
Labels: ready

#91 Adding first version of the CrossParcellationFC marker.
  docs/changes/latest.inc
  junifer/markers/__init__.py
  junifer/markers/crossparcellation_functional_connectivity.py
  junifer/markers/tests/test_crossparcellation_functional_connectivity.py
  junifer/markers/utils.py
Labels: ready

#122 chore: improve docs rendering
  docs/api/pipeline.rst
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/configs/juseless/datagrabbers/ixi_vbm.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/hcp.py
  junifer/markers/base.py
  junifer/markers/functional_connectivity_parcels.py
  junifer/markers/functional_connectivity_spheres.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/preprocess/base.py
  junifer/preprocess/confounds/fmriprep_confound_remover.py
  junifer/stats.py
  junifer/storage/base.py
  junifer/storage/sqlite.py
  junifer/testing/datagrabbers.py
  junifer/utils/fs.py
  junifer/utils/logging.py
Labels: documentation, ready

#123 Fix/bug_53
  docs/changes/latest.inc
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/base.py
  junifer/datagrabber/datalad_base.py
  junifer/datagrabber/hcp.py
  junifer/datagrabber/multiple.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/tests/test_base.py
  junifer/datagrabber/tests/test_datalad_base.py
  junifer/datagrabber/tests/test_multiple.py
  junifer/datagrabber/tests/test_pattern.py
  junifer/datagrabber/tests/test_pattern_datalad.py
  junifer/testing/datagrabbers.py
  junifer/utils/logging.py
  tools/create_bids_example_dataset.py
  tools/create_bids_example_dataset_sessions.py
Labels: ready

#102 [ENH]: Further Aggregation methods for SphereAggregation Marker
  docs/changes/latest.inc
  junifer/__init__.py
  junifer/external/__init__.py
  junifer/external/nilearn/__init__.py
  junifer/external/nilearn/junifer_nifti_spheres_masker.py
  junifer/external/nilearn/tests/test_junifer_nifti_spheres_masker.py
  junifer/markers/sphere_aggregation.py
  junifer/markers/tests/test_sphere_aggregation.py
Labels: enhancement, marker, ready

#130 [BUG]: CLI help has the wrong format
  junifer/api/cli.py
  tox.ini
Labels: bug, ready

#110 [ENH] Include tests for the `queue` command
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
Labels: enhancement, ready

#133 chore: parcellation table cleanup in docs
  docs/builtin.rst
Labels: documentation, ready

#135 Enh/default single output
  docs/changes/latest.inc
  examples/run_ets_rss_marker.py
  examples/run_junifer_julearn.py
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/markers/tests/test_collection.py
  junifer/markers/tests/test_crossparcellation_functional_connectivity.py
  junifer/markers/tests/test_ets_rss.py
  junifer/markers/tests/test_functional_connectivity_parcels.py
  junifer/markers/tests/test_functional_connectivity_spheres.py
  junifer/markers/tests/test_sphere_aggregation.py
  junifer/storage/base.py
  junifer/storage/pandas_base.py
  junifer/storage/sqlite.py
  junifer/storage/tests/test_sqlite.py
Labels: storage, ready

#79 [ENH]: Add support for masks (GM/WM/etc)
  docs/api/data.rst
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/data/__init__.py
  junifer/data/masks.py
  junifer/data/masks/vickery-patil/CAT12_IXI555_MNI152_TMP_GS_GMprob0.2_clean.nii.gz
  junifer/data/masks/vickery-patil/CAT12_IXI555_MNI152_TMP_GS_GMprob0.2_clean_3mm.nii.gz
  junifer/data/masks/vickery-patil/GMprob0.2_cortex_3mm_NA_rm.nii.gz
  junifer/data/parcellations.py
  junifer/data/tests/test_data_utils.py
  junifer/data/tests/test_masks.py
  junifer/data/utils.py
  junifer/markers/crossparcellation_functional_connectivity.py
  junifer/markers/ets_rss.py
  junifer/markers/functional_connectivity_parcels.py
  junifer/markers/functional_connectivity_spheres.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/markers/tests/test_ets_rss.py
  junifer/markers/tests/test_parcel_aggregation.py
  junifer/markers/tests/test_sphere_aggregation.py
Labels: enhancement, ready

#131 [ENH]: Allow ParcelAggregation to apply multiple parcellations at once
  docs/changes/latest.inc
  junifer/data/parcellations.py
  junifer/data/tests/test_parcellations.py
  junifer/markers/ets_rss.py
  junifer/markers/functional_connectivity_parcels.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/tests/test_parcel_aggregation.py
Labels: enhancement, ready

#120 [DOC]: Fill in built-in coordinates list
  docs/builtin.rst
Labels: documentation, ready
