Repository juaml/junifer, pull requests merged in 2023-01, with the labels that each got.

#165 chore: update docstrings
  docs/changes/latest.inc
  junifer/data/parcellations.py
  junifer/datagrabber/pattern.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/preprocess/confounds/fmriprep_confound_remover.py
Labels: documentation, ready

#167 [ENH]: Add Power coordinates
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/data/VOIs/meta/Power2011_MNI_VOIs.txt
  junifer/data/coordinates.py
Labels: enhancement, ready

#168 [ENH]: Add Dosenbach coordinates
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/data/VOIs/meta/Dosenbach2010_MNI_VOIs.txt
  junifer/data/coordinates.py
Labels: enhancement, ready

#107 [ENH] Refactor Functional Connectivity based markers
  docs/changes/latest.inc
  junifer/markers/__init__.py
  junifer/markers/falff/falff_parcels.py
  junifer/markers/functional_connectivity/__init__.py
  junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py
  junifer/markers/functional_connectivity/functional_connectivity_base.py
  junifer/markers/functional_connectivity/functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/functional_connectivity_spheres.py
  junifer/markers/functional_connectivity/tests/test_crossparcellation_functional_connectivity.py
  junifer/markers/functional_connectivity/tests/test_functional_connectivity_base.py
  junifer/markers/functional_connectivity/tests/test_functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/tests/test_functional_connectivity_spheres.py
  junifer/markers/functional_connectivity_spheres.py
Labels: enhancement, ready

#169 Marker/edge centric fc
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/markers/__init__.py
  junifer/markers/functional_connectivity/__init__.py
  junifer/markers/functional_connectivity/edge_functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/edge_functional_connectivity_spheres.py
  junifer/markers/functional_connectivity/tests/test_edge_functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/tests/test_edge_functional_connectivity_spheres.py
  junifer/markers/tests/test_marker_utils.py
  junifer/markers/utils.py
Labels: enhancement, ready

#155 [ENH]: Optimize HCP datagrabbers tests to improve CI running time.
  docs/changes/latest.inc
  junifer/datagrabber/hcp.py
  junifer/datagrabber/tests/test_hcp.py
Labels: enhancement, ready

#175 [ENH]: Support for multiple computed masks
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/data/__init__.py
  junifer/data/masks.py
  junifer/data/tests/test_masks.py
  junifer/markers/ets_rss.py
  junifer/markers/falff/falff_parcels.py
  junifer/markers/falff/falff_spheres.py
  junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py
  junifer/markers/functional_connectivity/functional_connectivity_base.py
  junifer/markers/functional_connectivity/functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/functional_connectivity_spheres.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/reho/reho_parcels.py
  junifer/markers/reho/reho_spheres.py
  junifer/markers/sphere_aggregation.py
  junifer/markers/tests/test_parcel_aggregation.py
Labels: enhancement
