Repository juaml/junifer, pull requests merged in 2023-12, with the labels that each got.

#277 [ENH]: Add support for ANTs via Docker
  docs/changes/newsfragments/277.misc
  docs/installation.rst
  junifer/api/cli.py
  junifer/api/res/ants/antsApplyTransforms
  junifer/api/res/ants/antsApplyTransformsToPoints
  junifer/api/res/ants/run_ants_docker.sh
  junifer/pipeline/utils.py
Labels: enhancement

#278 [BUG]: Fix FSL `std2imgcoord` I/O
  docs/changes/newsfragments/278.bugfix
  junifer/data/coordinates.py
Labels: bug

#279 [ENH]: Use stderr for external tool wrappers' output
  docs/changes/newsfragments/279.misc
  junifer/api/res/afni/run_afni_docker.sh
  junifer/api/res/ants/run_ants_docker.sh
  junifer/api/res/fsl/run_fsl_docker.sh
Labels: enhancement

#280 [BUG]: Fix FSL `std2imgcoord` source image
  docs/changes/newsfragments/280.bugfix
  junifer/data/coordinates.py
Labels: bug

#282 [BUG]: Propagate ReHo and fALFF maps' file paths
  docs/changes/newsfragments/282.bugfix
  junifer/markers/falff/falff_base.py
  junifer/markers/falff/falff_estimator.py
  junifer/markers/falff/tests/test_falff_estimator.py
  junifer/markers/reho/reho_base.py
  junifer/markers/reho/reho_estimator.py
  junifer/markers/reho/reho_parcels.py
  junifer/markers/reho/reho_spheres.py
  junifer/markers/reho/tests/test_reho_estimator.py
Labels: bug

#283 [BUG]: WorkDirManager does not accept string as workdir
  docs/changes/newsfragments/283.bugfix
  junifer/pipeline/workdir_manager.py
  junifer/storage/tests/test_utils.py
Labels: bug

#291 update: correct register_mask import in code example
  docs/changes/contributors.inc
  docs/changes/newsfragments/291.doc
  docs/extending/masks.rst
Labels: documentation

#288 [MAINT]: Make `BOLDWarper` tool-agnostic
  docs/changes/newsfragments/288.misc
  junifer/preprocess/__init__.py
  junifer/preprocess/bold_warper.py
  junifer/preprocess/fsl/__init__.py
  junifer/preprocess/fsl/apply_warper.py
  junifer/preprocess/tests/test_bold_warper.py
Labels: maintenance

#286 [BUG]: Correct path propagation logic for `ReHoEstimator` and `ALFFEstimator`
  docs/changes/newsfragments/286.bugfix
  junifer/markers/falff/falff_base.py
  junifer/markers/falff/falff_estimator.py
  junifer/markers/reho/reho_base.py
  junifer/markers/reho/reho_estimator.py
  junifer/markers/reho/reho_parcels.py
  junifer/markers/reho/reho_spheres.py
Labels: bug, marker, coordinate, template-space
