Repository juaml/junifer, pull requests merged in 2023-03, with the labels that each got.

#171 Markers/tsnr
  docs/builtin.rst
  docs/changes/latest.inc
  junifer/markers/__init__.py
  junifer/markers/temporal_snr/__init__.py
  junifer/markers/temporal_snr/temporal_snr_base.py
  junifer/markers/temporal_snr/temporal_snr_parcels.py
  junifer/markers/temporal_snr/temporal_snr_spheres.py
  junifer/markers/temporal_snr/tests/test_temporal_snr_base.py
  junifer/markers/temporal_snr/tests/test_temporal_snr_parcels.py
  junifer/markers/temporal_snr/tests/test_temporal_snr_spheres.py
Labels: enhancement, marker, ready

#195 [BUG]: The new "count" aggregation function does not respect multiple dimentions
  docs/changes/latest.inc
  junifer/stats.py
  junifer/tests/test_stats.py
Labels: bug, triage

#205 [ENH] Add copy button to documentation code blocks
  docs/changes/latest.inc
  docs/conf.py
  pyproject.toml
Labels: documentation, ready

#213 [ENH] Use and document `towncrier` for creating and maintaining changelogs
  .github/pull_request_template.md
  .github/workflows/docs-preview.yml
  docs/Makefile
  docs/_static/css/custom.css
  docs/changes/0.0.1.inc
  docs/changes/latest.inc
  docs/changes/newsfragments/.gitignore
  docs/changes/newsfragments/107.enh
  docs/changes/newsfragments/146.feature
  docs/changes/newsfragments/147.feature
  docs/changes/newsfragments/155.enh
  docs/changes/newsfragments/158.change
  docs/changes/newsfragments/159.bugfix
  docs/changes/newsfragments/160.enh
  docs/changes/newsfragments/163.feature
  docs/changes/newsfragments/165.enh
  docs/changes/newsfragments/166.doc
  docs/changes/newsfragments/167.feature
  docs/changes/newsfragments/168.feature
  docs/changes/newsfragments/175.feature
  docs/changes/newsfragments/177.enh
  docs/changes/newsfragments/181.change
  docs/changes/newsfragments/187.bugfix
  docs/changes/newsfragments/188.change
  docs/changes/newsfragments/189.bugfix
  docs/changes/newsfragments/190.change
  docs/changes/newsfragments/190.enh
  docs/changes/newsfragments/190.feature
  docs/changes/newsfragments/192.bugfix
  docs/changes/newsfragments/194.bugfix
  docs/changes/newsfragments/194.enh
  docs/changes/newsfragments/195.bugfix
  docs/changes/newsfragments/196.enh
  docs/changes/newsfragments/199.bugfix
  docs/changes/newsfragments/200.bugfix
  docs/changes/newsfragments/201.enh
  docs/changes/newsfragments/203.doc
  docs/changes/newsfragments/205.doc
  docs/changes/newsfragments/64.feature
  docs/contribution.rst
  docs/maintaining.rst
  docs/whats_new.rst
  pyproject.toml
Labels: documentation

#215 [FIX]: Make timeseries output 2D for `RSSETSMarker`
  docs/changes/newsfragments/215.bugfix
  junifer/markers/ets_rss.py
Labels: enhancement, marker, ready

#214 [ENH]: Add missing decorators for `BaseMarker` and `BasePreprocessor`
  docs/changes/newsfragments/214.enh
  junifer/markers/base.py
  junifer/preprocess/base.py
Labels: enhancement, ready

#185 [ENH]: Several bug fixes
  docs/changes/newsfragments/185.bugfix
  docs/changes/newsfragments/185.enh
  docs/changes/newsfragments/201.enh
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/datagrabber/datalad_base.py
  junifer/datareader/default.py
  junifer/datareader/tests/test_default_reader.py
  junifer/markers/base.py
  junifer/markers/tests/test_markers_base.py
  junifer/pipeline/pipeline_step_mixin.py
  junifer/pipeline/registry.py
  junifer/pipeline/tests/test_pipeline_step_mixin.py
  junifer/pipeline/tests/test_registry.py
  junifer/preprocess/base.py
  junifer/preprocess/confounds/fmriprep_confound_remover.py
  junifer/storage/hdf5.py
Labels: enhancement

#191 [BUG]: Relative paths in the `with` section on the YAML are relative to the CWD instead of the YAML file
  docs/changes/newsfragments/191.bugfix
  junifer/api/parser.py
  junifer/api/tests/test_parser.py
Labels: bug

#216 [ENH]: Rename (f)ALFF markers to be shorter and ALFF prefixed
  docs/builtin.rst
  docs/changes/newsfragments/187.bugfix
  docs/changes/newsfragments/216.change
  docs/whats_new.rst
  junifer/markers/__init__.py
  junifer/markers/falff/__init__.py
  junifer/markers/falff/falff_base.py
  junifer/markers/falff/falff_estimator.py
  junifer/markers/falff/falff_parcels.py
  junifer/markers/falff/falff_spheres.py
  junifer/markers/falff/tests/test_falff_estimator.py
  junifer/markers/falff/tests/test_falff_parcels.py
  junifer/markers/falff/tests/test_falff_spheres.py
  junifer/markers/parcel_aggregation.py
Labels: enhancement

#127 [BUG]: Storage URI in yaml config does not behave as I would expect.
  docs/changes/newsfragments/127.bugfix
  junifer/api/parser.py
  junifer/api/tests/test_parser.py
Labels: bug

#210 [ENH]: Add flowchart for users and improve docs
  docs/_static/css/custom.css
  docs/changes/newsfragments/210.doc
  docs/conf.py
  docs/help.rst
  docs/images/pipeline/pipeline.001.png
  docs/images/pipeline/pipeline.002.png
  docs/index.rst
  docs/links.inc
  docs/starting.rst
  docs/understanding/pipeline.rst
  docs/using/codeless.rst
  pyproject.toml
Labels: documentation

#183 [BUG]: HCP1200 datagrabber does not provide the correct BOLD files
  docs/changes/newsfragments/183.bugfix
  docs/changes/newsfragments/183.change
  junifer/datagrabber/hcp.py
  junifer/datagrabber/tests/test_hcp.py
  tools/create_hcp1200_example_dataset.py
Labels: bug, dataset

#217 Release Junifer 0.0.2
  docs/changes/newsfragments/107.enh
  docs/changes/newsfragments/127.bugfix
  docs/changes/newsfragments/146.feature
  docs/changes/newsfragments/147.feature
  docs/changes/newsfragments/155.enh
  docs/changes/newsfragments/158.change
  docs/changes/newsfragments/159.bugfix
  docs/changes/newsfragments/160.enh
  docs/changes/newsfragments/163.feature
  docs/changes/newsfragments/165.enh
  docs/changes/newsfragments/166.doc
  docs/changes/newsfragments/167.feature
  docs/changes/newsfragments/168.feature
  docs/changes/newsfragments/175.feature
  docs/changes/newsfragments/177.enh
  docs/changes/newsfragments/181.change
  docs/changes/newsfragments/183.bugfix
  docs/changes/newsfragments/183.change
  docs/changes/newsfragments/185.bugfix
  docs/changes/newsfragments/185.enh
  docs/changes/newsfragments/187.bugfix
  docs/changes/newsfragments/188.change
  docs/changes/newsfragments/189.bugfix
  docs/changes/newsfragments/190.change
  docs/changes/newsfragments/190.enh
  docs/changes/newsfragments/190.feature
  docs/changes/newsfragments/191.bugfix
  docs/changes/newsfragments/192.bugfix
  docs/changes/newsfragments/194.bugfix
  docs/changes/newsfragments/194.enh
  docs/changes/newsfragments/195.bugfix
  docs/changes/newsfragments/196.enh
  docs/changes/newsfragments/199.bugfix
  docs/changes/newsfragments/200.bugfix
  docs/changes/newsfragments/201.enh
  docs/changes/newsfragments/203.doc
  docs/changes/newsfragments/205.doc
  docs/changes/newsfragments/210.doc
  docs/changes/newsfragments/214.enh
  docs/changes/newsfragments/215.bugfix
  docs/changes/newsfragments/216.change
  docs/changes/newsfragments/218.doc
  docs/changes/newsfragments/64.feature
  docs/whats_new.rst
Labels: ready
