Repository juaml/junifer, pull requests merged in 2023-10, with the labels that each got.

#253 [ENH]: Bump dependencies
  conda-env.yml
  docs/changes/newsfragments/253.misc
  docs/contribution.rst
  docs/installation.rst
  ignore_words.txt
  junifer/external/nilearn/junifer_nifti_spheres_masker.py
  pyproject.toml
Labels: enhancement

#245 [ENH]: Support for `Power 2013` coordinates
  docs/builtin.rst
  docs/changes/newsfragments/245.change
  docs/changes/newsfragments/245.feature
  junifer/data/VOIs/meta/Power2013_MNI_VOIs.tsv
  junifer/data/coordinates.py
Labels: enhancement, ready, coordinate

#251 [BUG]: `extMDN` coordinates are falsely registered as `extDMN` coordinates in `junifer`
  docs/builtin.rst
  docs/changes/newsfragments/251.doc
Labels: bug, coordinate

#182 [ENH]: Add support for subject(s) file for `junifer run`
  docs/changes/newsfragments/182.enh
  docs/using/running.rst
  junifer/api/cli.py
  junifer/api/functions.py
  junifer/api/tests/test_cli.py
  junifer/api/tests/test_functions.py
  junifer/datagrabber/base.py
  junifer/datagrabber/tests/test_base.py
Labels: enhancement, dataset, ready
