Repository juaml/junifer, pull requests merged in 2024-11, with the labels that each got.

#391 [ENH]: Refactor `Singleton` as a metaclass
  docs/changes/newsfragments/391.misc
  junifer/conftest.py
  junifer/data/coordinates/_coordinates.py
  junifer/data/masks/_masks.py
  junifer/data/parcellations/_parcellations.py
  junifer/data/pipeline_data_registry_base.py
  junifer/datagrabber/hcp1200/tests/test_hcp1200.py
  junifer/markers/falff/_afni_falff.py
  junifer/markers/falff/_junifer_falff.py
  junifer/markers/reho/_afni_reho.py
  junifer/markers/reho/_junifer_reho.py
  junifer/pipeline/pipeline_component_registry.py
  junifer/pipeline/workdir_manager.py
  junifer/utils/singleton.py
Labels: enhancement

#389 Bypass cleanup of temporary dirs if needed
  docs/changes/newsfragments/389.enh
  junifer/pipeline/tests/test_workdir_manager.py
  junifer/pipeline/workdir_manager.py
Labels: enhancement

#392 [ENH]: Introduce `junfer.typing` module
  README.md
  docs/changes/newsfragments/392.feature
  docs/extending/dependencies.rst
  docs/extending/marker.rst
  junifer/__init__.pyi
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/datagrabber/multiple.py
  junifer/markers/base.py
  junifer/markers/brainprint.py
  junifer/markers/complexity/complexity_base.py
  junifer/markers/ets_rss.py
  junifer/markers/falff/_afni_falff.py
  junifer/markers/falff/_junifer_falff.py
  junifer/markers/falff/falff_base.py
  junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py
  junifer/markers/functional_connectivity/functional_connectivity_base.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/reho/_afni_reho.py
  junifer/markers/reho/_junifer_reho.py
  junifer/markers/reho/reho_base.py
  junifer/markers/sphere_aggregation.py
  junifer/markers/temporal_snr/temporal_snr_base.py
  junifer/onthefly/_brainprint.py
  junifer/onthefly/read_transform.py
  junifer/pipeline/marker_collection.py
  junifer/pipeline/pipeline_component_registry.py
  junifer/pipeline/tests/test_pipeline_step_mixin.py
  junifer/pipeline/tests/test_workdir_manager.py
  junifer/preprocess/confounds/fmriprep_confound_remover.py
  junifer/preprocess/smoothing/_afni_smoothing.py
  junifer/preprocess/smoothing/_fsl_smoothing.py
  junifer/preprocess/smoothing/_nilearn_smoothing.py
  junifer/preprocess/smoothing/smoothing.py
  junifer/preprocess/warping/_ants_warper.py
  junifer/preprocess/warping/_fsl_warper.py
  junifer/preprocess/warping/space_warper.py
  junifer/preprocess/warping/tests/test_space_warper.py
  junifer/typing/__init__.py
  junifer/typing/__init__.pyi
  junifer/typing/_typing.py
Labels: enhancement, maintenance

#390 [ENH]: Update `Warp` datatype schema and logic
  docs/changes/newsfragments/390.change
  docs/changes/newsfragments/390.enh
  docs/extending/dependencies.rst
  docs/understanding/preprocess.rst
  junifer/data/coordinates/_ants_coordinates_warper.py
  junifer/data/coordinates/_coordinates.py
  junifer/data/coordinates/_fsl_coordinates_warper.py
  junifer/data/masks/_ants_mask_warper.py
  junifer/data/masks/_fsl_mask_warper.py
  junifer/data/masks/_masks.py
  junifer/data/parcellations/_ants_parcellation_warper.py
  junifer/data/parcellations/_fsl_parcellation_warper.py
  junifer/data/parcellations/_parcellations.py
  junifer/data/utils.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/base.py
  junifer/datagrabber/datalad_base.py
  junifer/datagrabber/dmcc13_benchmark.py
  junifer/datagrabber/hcp1200/hcp1200.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/pattern_validation_mixin.py
  junifer/datagrabber/tests/test_dmcc13_benchmark.py
  junifer/pipeline/pipeline_step_mixin.py
  junifer/pipeline/update_meta_mixin.py
  junifer/preprocess/warping/_ants_warper.py
  junifer/preprocess/warping/_fsl_warper.py
  junifer/preprocess/warping/space_warper.py
  tools/create_dmcc13_benchmark_example_dataset.py
  tools/create_hcp1200_example_dataset.py
Labels: documentation, enhancement, dataset, marker, preprocess, parcellation, coordinate, template-space

#388 [BUG]: Coordinates transforms to native space using `ANTs` are off
  docs/changes/newsfragments/388.bugfix
  junifer/data/coordinates/_ants_coordinates_warper.py
  junifer/data/coordinates/_coordinates.py
Labels: bug, coordinate

#398 [BUG]: Fix metadata update for `MultipleDataGrabber`
  docs/changes/newsfragments/398.bugfix
  junifer/datagrabber/multiple.py
  junifer/datagrabber/pattern.py
  junifer/datagrabber/pattern_validation_mixin.py
  junifer/datagrabber/tests/test_datalad_base.py
  junifer/datagrabber/tests/test_multiple.py
  junifer/datagrabber/tests/test_pattern_datalad.py
  junifer/typing/__init__.pyi
  junifer/typing/_typing.py
  tools/create_bids_example_dataset.py
  tools/create_bids_example_dataset_sessions.py
Labels: bug, dataset

#401 [ENH]: Introduce `ConfigManager`
  docs/changes/newsfragments/401.feature
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/cli/cli.py
  junifer/cli/parser.py
  junifer/data/_dispatch.py
  junifer/data/masks/_masks.py
  junifer/data/template_spaces.py
  junifer/stats.py
  junifer/storage/utils.py
  junifer/testing/datagrabbers.py
  junifer/typing/__init__.pyi
  junifer/typing/_typing.py
  junifer/utils/__init__.pyi
  junifer/utils/_config.py
  junifer/utils/helpers.py
  junifer/utils/logging.py
  junifer/utils/singleton.py
  junifer/utils/tests/test_config.py
Labels: enhancement

#403 [ENH]: Use `junifer.utils.config` to skip dataset id and dirty checks (time consuming)
  docs/changes/newsfragments/403.enh
  docs/conf.py
  junifer/datagrabber/datalad_base.py
  junifer/datagrabber/tests/test_datalad_base.py
Labels: dataset

#402 [ENH]: Allow `workdir` to forward parameters from YAML
  docs/changes/newsfragments/402.change
  docs/changes/newsfragments/402.enh
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/cli/cli.py
  junifer/cli/parser.py
  junifer/pipeline/workdir_manager.py
Labels: enhancement

#407 [ENH]: Introduce `BOLD.reference` nested data type
  docs/changes/newsfragments/407.feature
  junifer/data/coordinates/_fsl_coordinates_warper.py
  junifer/data/masks/_ants_mask_warper.py
  junifer/data/masks/_fsl_mask_warper.py
  junifer/data/parcellations/_ants_parcellation_warper.py
  junifer/data/parcellations/_fsl_parcellation_warper.py
  junifer/datagrabber/pattern_validation_mixin.py
  junifer/preprocess/warping/_ants_warper.py
  junifer/preprocess/warping/_fsl_warper.py
Labels: enhancement

#405 Provide data in all spaces for AOMIC datasets
  docs/changes/newsfragments/405.change
  docs/changes/newsfragments/405.enh
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/aomic/tests/test_id1000.py
  junifer/datagrabber/aomic/tests/test_piop1.py
  junifer/datagrabber/aomic/tests/test_piop2.py
  tools/create_aomic1000_example_dataset.py
  tools/create_aomicpiop1_example_dataset.py
  tools/create_aomicpiop2_example_dataset.py
Labels: dataset
