Repository juaml/junifer, pull requests merged in 2024-10, with the labels that each got.

#371 Add `emomatching` task to AOMIC PIOP2 datagrabber
  docs/changes/newsfragments/370.bugfix
  junifer/datagrabber/aomic/piop2.py
Labels: bug, dataset

#372 [MAINT]: Drop Python 3.8 and support Python 3.13
  .github/workflows/ci-docs.yml
  .github/workflows/ci.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pypi.yml
  docs/changes/newsfragments/372.misc
  pyproject.toml
  tox.ini
Labels: maintenance

#373 [CI]: Add Dockerfile for building docs
  .dockerignore
  .github/workflows/docker-docs-publish.yml
  Dockerfile-docs
  docs/changes/newsfragments/373.misc
Labels: maintenance

#368 [ENH]: Use datalad human-template-xfms dataset for `junifer.data.get_xfm()`
  docs/changes/newsfragments/368.enh
  junifer/data/template_spaces.py
Labels: enhancement, template-space

#374 [CI]: Adopt custom CI image for junifer docs
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  docs/changes/newsfragments/374.misc
Labels: documentation, maintenance

#382 [CI]: Add Dockerfile for CI
  .github/workflows/docker-ci-publish.yml
  Dockerfile-ci
  docs/changes/newsfragments/382.misc
Labels: maintenance

#384 [MAINT]: Improve docs publishing
  .github/workflows/docs.yml
  docs/changes/newsfragments/384.misc
Labels: maintenance

#362 [ENH]: Introduce `PipelineComponentRegistry`
  docs/api/pipeline.rst
  docs/changes/newsfragments/362.feature
  junifer/__init__.pyi
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/datagrabber/aomic/piop2.py
  junifer/pipeline/__init__.pyi
  junifer/pipeline/pipeline_component_registry.py
  junifer/pipeline/registry.py
  junifer/pipeline/tests/test_pipeline_component_registry.py
  junifer/pipeline/tests/test_registry.py
  junifer/testing/__init__.pyi
  junifer/testing/registry.py
  junifer/testing/tests/test_testing_registry.py
Labels: enhancement

#383 [CI]: Adopt custom CI image for junifer test
  .github/workflows/ci.yml
  docs/changes/newsfragments/383.misc
  tox.ini
Labels: maintenance
