Repository juaml/junifer, pull requests merged in 2024-09, with the labels that each got.

#358 [DOC]: Improve Sphinx configuration and extensions
  .github/workflows/ci.yml
  docs/Makefile
  docs/changes/newsfragments/358.doc
  docs/conf.py
  docs/sphinxext/gh_substitutions.py
  docs/whats_new.rst
  pyproject.toml
Labels: documentation

#361 [ENH]: Introduce new `cli` sub-package
  docs/api/api.rst
  docs/api/cli.rst
  docs/api/index.rst
  docs/changes/newsfragments/361.misc
  junifer/__init__.py
  junifer/api/__init__.py
  junifer/api/decorators.py
  junifer/api/functions.py
  junifer/api/tests/test_functions.py
  junifer/cli/__init__.py
  junifer/cli/cli.py
  junifer/cli/parser.py
  junifer/cli/tests/data/gmd_mean.yaml
  junifer/cli/tests/data/gmd_mean_htcondor.yaml
  junifer/cli/tests/data/partly_cloudy_agg_mean_tian.yml
  junifer/cli/tests/test_cli.py
  junifer/cli/tests/test_cli_utils.py
  junifer/cli/tests/test_parser.py
  junifer/cli/utils.py
  junifer/utils/__init__.py
  junifer/utils/_yaml.py
  pyproject.toml
Labels: maintenance

#367 [ENH]: Allow for external modules to import other files
  docs/changes/newsfragments/367.enh
  docs/extending/extension.rst
  junifer/cli/parser.py
Labels: enhancement

#369 [BUG]: Typo for `fMRIPrepConfoundRemover` pipeline registration
  docs/changes/newsfragments/369.bugfix
  junifer/pipeline/registry.py
Labels: bug
