Repository juaml/junifer, pull requests merged in 2024-04, with the labels that each got.

#317 [DOC]: Improve documentation
  docs/builtin.rst
  docs/changes/newsfragments/317.doc
  docs/contribution.rst
  docs/extending/coordinates.rst
  docs/extending/datagrabber.rst
  docs/extending/dependencies.rst
  docs/extending/extension.rst
  docs/extending/index.rst
  docs/extending/marker.rst
  docs/extending/masks.rst
  docs/extending/parcellations.rst
  docs/extending/preprocessor.rst
  docs/installation.rst
  docs/links.inc
  docs/starting.rst
  docs/understanding/data.rst
  docs/understanding/datagrabber.rst
  docs/understanding/datareader.rst
  docs/understanding/index.rst
  docs/understanding/marker.rst
  docs/understanding/pipeline.rst
  docs/understanding/preprocess.rst
  docs/understanding/storage.rst
  docs/using/codeless.rst
  docs/using/index.rst
  docs/using/masks.rst
  docs/using/queueing.rst
Labels: documentation

#299 [ENH]: Add support for on-the-fly template space transformation
  .github/workflows/docs-preview.yml
  docs/changes/newsfragments/299.change
  docs/changes/newsfragments/299.enh
  docs/changes/newsfragments/299.feature
  examples/yamls/partly_cloudy_agg_mean_tian.yml
  junifer/api/tests/data/partly_cloudy_agg_mean_tian.yml
  junifer/api/tests/test_cli.py
  junifer/api/tests/test_functions.py
  junifer/data/coordinates.py
  junifer/data/masks.py
  junifer/data/parcellations.py
  junifer/data/template_spaces.py
  junifer/data/tests/test_masks.py
  junifer/data/tests/test_parcellations.py
  junifer/data/tests/test_template_spaces.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/dmcc13_benchmark.py
  junifer/datagrabber/hcp1200/hcp1200.py
  junifer/markers/falff/tests/test_falff_parcels.py
  junifer/markers/falff/tests/test_falff_spheres.py
  junifer/markers/functional_connectivity/tests/test_crossparcellation_functional_connectivity.py
  junifer/markers/functional_connectivity/tests/test_edge_functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/tests/test_edge_functional_connectivity_spheres.py
  junifer/markers/functional_connectivity/tests/test_functional_connectivity_parcels.py
  junifer/markers/functional_connectivity/tests/test_functional_connectivity_spheres.py
  junifer/markers/reho/tests/test_reho_parcels.py
  junifer/markers/temporal_snr/tests/test_temporal_snr_parcels.py
  junifer/markers/temporal_snr/tests/test_temporal_snr_spheres.py
  junifer/markers/tests/test_collection.py
  junifer/markers/tests/test_ets_rss.py
  junifer/markers/tests/test_parcel_aggregation.py
  junifer/markers/tests/test_sphere_aggregation.py
Labels: enhancement, parcellation, mask, template-space

#320 [FIX]: Change all `probseg_` appearances with `VBM_` for consistency
  docs/changes/newsfragments/320.change
  docs/changes/newsfragments/320.fix
  junifer/api/functions.py
  junifer/configs/juseless/datagrabbers/tests/test_ucla.py
  junifer/configs/juseless/datagrabbers/ucla.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/aomic/tests/test_id1000.py
  junifer/datagrabber/aomic/tests/test_piop1.py
  junifer/datagrabber/aomic/tests/test_piop2.py
  junifer/datagrabber/dmcc13_benchmark.py
  junifer/datagrabber/tests/test_dmcc13_benchmark.py
  junifer/datagrabber/utils.py
  junifer/markers/parcel_aggregation.py
  junifer/markers/sphere_aggregation.py
  junifer/preprocess/warping/space_warper.py
Labels: enhancement, dataset

#322 [BUG]: subject ID truncated incorrectly in condor submit dag file
  docs/changes/newsfragments/322.bugfix
  junifer/api/cli.py
  junifer/api/tests/test_cli.py
Labels: bug

#325 Follow the datasets BIDS convention for participants/sessions
  docs/changes/newsfragments/325.change
  junifer/configs/juseless/datagrabbers/aomic_id1000_vbm.py
  junifer/configs/juseless/datagrabbers/camcan_vbm.py
  junifer/configs/juseless/datagrabbers/ixi_vbm.py
  junifer/configs/juseless/datagrabbers/ucla.py
  junifer/configs/juseless/datagrabbers/ukb_vbm.py
  junifer/data/tests/test_masks.py
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/aomic/tests/test_id1000.py
  junifer/datagrabber/aomic/tests/test_piop1.py
  junifer/datagrabber/aomic/tests/test_piop2.py
  junifer/datagrabber/dmcc13_benchmark.py
  junifer/datagrabber/tests/test_dmcc13_benchmark.py
  junifer/preprocess/ants/tests/test_ants_apply_transforms_warper.py
  junifer/preprocess/tests/test_bold_warper.py
  junifer/preprocess/warping/tests/test_space_warper.py
Labels: enhancement, dataset

#273 [ENH]: Specify which shell to use when using `junifer queue`
  docs/changes/newsfragments/273.feature
  docs/changes/newsfragments/320.fix
  docs/changes/newsfragments/321.fix
  docs/whats_new.rst
  junifer/api/queue_context/gnu_parallel_local_adapter.py
  junifer/api/queue_context/htcondor_adapter.py
  junifer/api/queue_context/tests/test_gnu_parallel_local_adapter.py
  junifer/api/queue_context/tests/test_htcondor_adapter.py
  junifer/api/res/run_conda.bash
  junifer/api/res/run_conda.zsh
  junifer/api/res/run_venv.bash
  junifer/api/res/run_venv.zsh
  junifer/configs/juseless/datagrabbers/aomic_id1000_vbm.py
  junifer/configs/juseless/datagrabbers/ixi_vbm.py
  junifer/datagrabber/aomic/tests/test_id1000.py
Labels: enhancement

#161 [ENH]: Smoothing images as a preprocessing step
  docs/changes/newsfragments/161.feature
  junifer/preprocess/__init__.py
  junifer/preprocess/smoothing/__init__.py
  junifer/preprocess/smoothing/_afni_smoothing.py
  junifer/preprocess/smoothing/_fsl_smoothing.py
  junifer/preprocess/smoothing/_nilearn_smoothing.py
  junifer/preprocess/smoothing/smoothing.py
  junifer/preprocess/smoothing/tests/test_smoothing.py
Labels: enhancement, preprocess

#324 [BUG]: Extra dimension added to parcellation after warping to another template space via ANTs
  docs/changes/newsfragments/324.bugfix
  junifer/markers/parcel_aggregation.py
Labels: bug, parcellation, template-space

#323 [ENH]: Add `junifer list-elements` for listing out elements of an YAML's DataGrabber
  docs/changes/newsfragments/323.feature
  junifer/api/cli.py
  junifer/api/functions.py
  junifer/api/tests/test_cli.py
  junifer/api/tests/test_functions.py
Labels: enhancement

#115 [DOC]: Change `__init__.py` docstrings to reflect sub-packages
  docs/api/nilearn.rst
  docs/api/onthefly.rst
  docs/changes/newsfragments/115.doc
  junifer/api/__init__.py
  junifer/api/queue_context/__init__.py
  junifer/configs/__init__.py
  junifer/configs/juseless/__init__.py
  junifer/configs/juseless/datagrabbers/__init__.py
  junifer/data/__init__.py
  junifer/data/coordinates.py
  junifer/data/masks.py
  junifer/data/parcellations.py
  junifer/data/template_spaces.py
  junifer/datagrabber/__init__.py
  junifer/datareader/__init__.py
  junifer/external/__init__.py
  junifer/external/nilearn/__init__.py
  junifer/markers/__init__.py
  junifer/onthefly/__init__.py
  junifer/pipeline/__init__.py
  junifer/preprocess/__init__.py
  junifer/stats.py
  junifer/storage/__init__.py
  junifer/testing/__init__.py
  junifer/testing/datagrabbers.py
  junifer/utils/__init__.py
Labels: documentation

#330 [DOC]: Add missing types in DataGrabber `types` docstrings
  docs/changes/newsfragments/330.doc
  junifer/datagrabber/aomic/id1000.py
  junifer/datagrabber/aomic/piop1.py
  junifer/datagrabber/aomic/piop2.py
  junifer/datagrabber/dmcc13_benchmark.py
Labels: documentation

#332 [BUG]: `junifer reset` fails as it tries to delete `junifer_jobs` directory
  docs/changes/newsfragments/332.bugfix
  junifer/api/functions.py
Labels: bug

#336 [MAINT]: Remove deprecations from 0.0.3 and 0.0.4
  docs/builtin.rst
  docs/changes/newsfragments/336.removal
  docs/whats_new.rst
  junifer/data/coordinates.py
  junifer/data/masks.py
  junifer/data/tests/test_masks.py
  junifer/preprocess/__init__.py
  junifer/preprocess/ants/__init__.py
  junifer/preprocess/ants/ants_apply_transforms_warper.py
  junifer/preprocess/ants/tests/test_ants_apply_transforms_warper.py
  junifer/preprocess/bold_warper.py
  junifer/preprocess/fsl/__init__.py
  junifer/preprocess/fsl/apply_warper.py
  junifer/preprocess/fsl/tests/test_apply_warper.py
  junifer/preprocess/tests/test_bold_warper.py
Labels: maintenance
