Repository juaml/junifer, pull requests merged in 2025-03, with the labels that each got.

#431 [BUG]: Cannot fetch Power2011 coordinates
  docs/changes/newsfragments/431.bugfix
  junifer/data/coordinates/_coordinates.py
Labels: bug, coordinate

#434 Use hexsha to verify junifer-data integrity
  docs/changes/newsfragments/434.enh
  junifer/data/coordinates/_coordinates.py
  junifer/data/masks/_masks.py
  junifer/data/parcellations/_parcellations.py
  junifer/data/template_spaces.py
  junifer/data/utils.py
  pyproject.toml
Labels: enhancement

#436 Power2011 and Power2013 files contain the same coordinates with mismatched ROI numbering
  docs/builtin.rst
  docs/changes/newsfragments/436.bugfix
  junifer/data/coordinates/_coordinates.py
Labels: invalid, coordinate

#438 [CI]: Bump `junifer-data` to v2 for building Docker images
  Dockerfile-ci
  Dockerfile-docs
  docs/changes/newsfragments/438.misc
Labels: maintenance

#437 [MAINT]: Bump `junifer-data` version to v2
  .github/workflows/ci.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  docs/builtin.rst
  docs/changes/newsfragments/437.misc
  junifer/data/coordinates/_coordinates.py
  junifer/data/utils.py
Labels: maintenance

#439 [BUG]: Correct methods for `*_data()` functions
  docs/changes/newsfragments/439.bugfix
  junifer/data/_dispatch.py
Labels: bug
