Repository juaml/junifer, pull requests merged in 2025-09, with the labels that each got.

#458 [ENH]: Introduce `MapsRegistry`
  conda-env.yml
  docs/builtin.rst
  docs/changes/newsfragments/458.change
  docs/changes/newsfragments/458.feature
  docs/changes/newsfragments/458.misc
  docs/extending/index.rst
  docs/extending/maps.rst
  junifer/data/__init__.pyi
  junifer/data/_dispatch.py
  junifer/data/maps/__init__.py
  junifer/data/maps/__init__.pyi
  junifer/data/maps/_ants_maps_warper.py
  junifer/data/maps/_fsl_maps_warper.py
  junifer/data/maps/_maps.py
  junifer/data/maps/tests/test_maps.py
  junifer/data/masks/_masks.py
  junifer/data/parcellations/_parcellations.py
  pyproject.toml
Labels: enhancement, maps

#454 Fix check for FSL
  docs/changes/newsfragments/454.bugfix
  junifer/pipeline/utils.py
Labels: bug

#465 [CI]: Bump `junifer-data` to v4 for building Docker images
  Dockerfile-ci
  Dockerfile-docs
  docs/changes/newsfragments/465.misc
Labels: maintenance

#467 [CI]: Disable FSL installation for junifer-ci Docker image
  Dockerfile-ci
  docs/changes/newsfragments/467.misc
Labels: maintenance
